"""Driver protocol shared by all backend chat sites.

Each driver translates OpenAI/Anthropic chat-completions requests into
the target site's native chat API, and yields back OpenAI-style stream
chunks. The reverse-proxy server is driver-agnostic.
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import AsyncIterator, Literal


# --- Canonical OpenAI-shaped types we use internally -----------------------

@dataclass
class Message:
    role: Literal["system", "user", "assistant", "tool"]
    content: str
    name: str | None = None
    tool_call_id: str | None = None


@dataclass
class ToolSpec:
    name: str
    description: str
    parameters: dict  # JSON schema


@dataclass
class ChatRequest:
    """Internal canonical request. Translated FROM OpenAI/Anthropic in app.py
    and translated TO site-native by each driver."""
    model: str
    messages: list[Message]
    tools: list[ToolSpec] = field(default_factory=list)
    max_tokens: int = 4000
    temperature: float = 0.7
    top_p: float = 1.0
    stream: bool = True


# --- Stream chunk types ----------------------------------------------------

@dataclass
class TextDelta:
    """Plain assistant text chunk (no tool call)."""
    text: str


@dataclass
class ToolCallStart:
    """Beginning of a tool_call fence detected in the stream."""
    call_id: str  # generated by us, e.g. "call_<uuid8>"
    tool_name: str | None = None  # filled when known


@dataclass
class ToolCallArgsDelta:
    """Streaming JSON-arg delta for an in-progress tool call."""
    call_id: str
    arguments_delta: str  # raw JSON fragment


@dataclass
class ToolCallEnd:
    """Tool call fully assembled."""
    call_id: str
    tool_name: str
    arguments: dict  # parsed


@dataclass
class StreamDone:
    finish_reason: Literal["stop", "length", "tool_calls", "content_filter", "error"]
    error_message: str | None = None


StreamChunk = TextDelta | ToolCallStart | ToolCallArgsDelta | ToolCallEnd | StreamDone


# --- Driver interface ------------------------------------------------------

class ChatDriver(ABC):
    """Each concrete driver implements one upstream free chat site."""

    name: str  # e.g. "overchat", "miniapps"
    supported_models: list[str]  # internal model ids this driver handles

    @abstractmethod
    async def chat_stream(self, req: ChatRequest) -> AsyncIterator[StreamChunk]:
        """Yield stream chunks. Caller is responsible for converting to
        OpenAI/Anthropic SSE wire format."""
        ...

    @abstractmethod
    async def health_check(self) -> bool:
        """Quick non-billable check (e.g. echo with 1 token max).
        Returns True if driver is currently usable."""
        ...
